"""Ilk sema"""

import sqlalchemy as sa
from alembic import op

revision = "9100372fb039"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "denetim",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("zaman", sa.Integer(), nullable=False),
        sa.Column("kullanici_id", sa.String(), nullable=True),
        sa.Column("islem", sa.String(), nullable=False),
        sa.Column("kaynak_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_denetim_zaman"), "denetim", ["zaman"], unique=False
    )
    op.create_table(
        "kullanicilar",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("parola_ozeti", sa.Text(), nullable=False),
        sa.Column("rol", sa.String(), nullable=False),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column("mfa_sirri", sa.Text(), nullable=True),
        sa.Column("son_mfa_adimi", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "oturumlar",
        sa.Column("ozet", sa.String(), nullable=False),
        sa.Column("kullanici_id", sa.String(), nullable=False),
        sa.Column("csrf_ozeti", sa.String(), nullable=False),
        sa.Column("olusturma", sa.Integer(), nullable=False),
        sa.Column("son_erisim", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kullanici_id"],
            ["kullanicilar.id"],
        ),
        sa.PrimaryKeyConstraint("ozet"),
    )
    op.create_table(
        "uzmanlar",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kullanici_id", sa.String(), nullable=False),
        sa.Column("ad", sa.String(length=150), nullable=False),
        sa.Column("sehir", sa.String(length=80), nullable=False),
        sa.Column("ilce", sa.String(length=80), nullable=False),
        sa.Column("biyografi", sa.Text(), nullable=False),
        sa.Column("ucret", sa.Integer(), nullable=False),
        sa.Column("deneyim_yili", sa.Integer(), nullable=False),
        sa.Column("ekoller", sa.JSON(), nullable=False),
        sa.Column("kitle", sa.JSON(), nullable=False),
        sa.Column("formatlar", sa.JSON(), nullable=False),
        sa.Column("uzmanliklar", sa.JSON(), nullable=False),
        sa.Column("egitim", sa.JSON(), nullable=False),
        sa.Column("kurumlar", sa.JSON(), nullable=False),
        sa.Column("calisma_saatleri", sa.JSON(), nullable=False),
        sa.Column("adres", sa.Text(), nullable=False),
        sa.Column("onayli", sa.Boolean(), nullable=False),
        sa.Column("arsivli", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kullanici_id"],
            ["kullanicilar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kullanici_id"),
    )
    op.create_index(
        op.f("ix_uzmanlar_onayli"), "uzmanlar", ["onayli"], unique=False
    )
    op.create_index(
        op.f("ix_uzmanlar_sehir"), "uzmanlar", ["sehir"], unique=False
    )
    op.create_table(
        "randevular",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("uzman_id", sa.String(), nullable=False),
        sa.Column("baslangic", sa.Integer(), nullable=False),
        sa.Column("danisan_sifreli", sa.Text(), nullable=False),
        sa.Column("durum", sa.String(), nullable=False),
        sa.Column("olusturma", sa.Integer(), nullable=False),
        sa.Column("aydinlatma_surumu", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uzman_id"],
            ["uzmanlar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_randevular_baslangic"),
        "randevular",
        ["baslangic"],
        unique=False,
    )
    op.create_index(
        op.f("ix_randevular_uzman_id"),
        "randevular",
        ["uzman_id"],
        unique=False,
    )
    op.create_index(
        "uq_aktif_randevu",
        "randevular",
        ["uzman_id", "baslangic"],
        unique=True,
        sqlite_where=sa.text("durum IN ('bekliyor', 'onaylandi')"),
        postgresql_where=sa.text("durum IN ('bekliyor', 'onaylandi')"),
    )
    op.create_table(
        "tavsiyeler",
        sa.Column("veren_id", sa.String(), nullable=False),
        sa.Column("alan_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alan_id"],
            ["uzmanlar.id"],
        ),
        sa.ForeignKeyConstraint(
            ["veren_id"],
            ["uzmanlar.id"],
        ),
        sa.PrimaryKeyConstraint("veren_id", "alan_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tavsiyeler")
    op.drop_index(
        "uq_aktif_randevu",
        table_name="randevular",
        sqlite_where=sa.text("durum IN ('bekliyor', 'onaylandi')"),
        postgresql_where=sa.text("durum IN ('bekliyor', 'onaylandi')"),
    )
    op.drop_index(op.f("ix_randevular_uzman_id"), table_name="randevular")
    op.drop_index(op.f("ix_randevular_baslangic"), table_name="randevular")
    op.drop_table("randevular")
    op.drop_index(op.f("ix_uzmanlar_sehir"), table_name="uzmanlar")
    op.drop_index(op.f("ix_uzmanlar_onayli"), table_name="uzmanlar")
    op.drop_table("uzmanlar")
    op.drop_table("oturumlar")
    op.drop_table("kullanicilar")
    op.drop_index(op.f("ix_denetim_zaman"), table_name="denetim")
    op.drop_table("denetim")
    # ### end Alembic commands ###
